/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client;

import at.mic.superset.swagger.ApiException;
import at.mic.superset.swagger.client.model.InlineResponse20038;
import at.mic.superset.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CurrentUserApi
 */
@Ignore
public class CurrentUserApiTest {

    private final CurrentUserApi api = new CurrentUserApi();

    /**
     * 
     *
     * Returns the user object corresponding to the agent making the request, or returns a 401 error if the user is unauthenticated.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1MeGetTest() throws ApiException {
        InlineResponse20038 response = api.apiV1MeGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the user roles corresponding to the agent making the request, or returns a 401 error if the user is unauthenticated.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1MeRolesGetTest() throws ApiException {
        InlineResponse20038 response = api.apiV1MeRolesGet();

        // TODO: test validations
    }
}
