/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client;

import at.mic.superset.swagger.ApiException;
import at.mic.superset.swagger.client.model.InlineResponse20022;
import at.mic.superset.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmbeddedDashboardApi
 */
@Ignore
public class EmbeddedDashboardApiTest {

    private final EmbeddedDashboardApi api = new EmbeddedDashboardApi();

    /**
     * 
     *
     * Get a report schedule log
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1EmbeddedDashboardUuidGetTest() throws ApiException {
        String uuid = null;
        InlineResponse20022 response = api.apiV1EmbeddedDashboardUuidGet(uuid);

        // TODO: test validations
    }
}
