/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DatabaseRestApiGet
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-08-29T14:48:42.974+02:00[Europe/Berlin]")
public class DatabaseRestApiGet {
  @SerializedName("allow_ctas")
  private Boolean allowCtas = null;

  @SerializedName("allow_cvas")
  private Boolean allowCvas = null;

  @SerializedName("allow_dml")
  private Boolean allowDml = null;

  @SerializedName("allow_file_upload")
  private Boolean allowFileUpload = null;

  @SerializedName("allow_multi_schema_metadata_fetch")
  private Boolean allowMultiSchemaMetadataFetch = null;

  @SerializedName("allow_run_async")
  private Boolean allowRunAsync = null;

  @SerializedName("backend")
  private Object backend = null;

  @SerializedName("cache_timeout")
  private Integer cacheTimeout = null;

  @SerializedName("configuration_method")
  private String configurationMethod = null;

  @SerializedName("database_name")
  private String databaseName = null;

  @SerializedName("encrypted_extra")
  private String encryptedExtra = null;

  @SerializedName("expose_in_sqllab")
  private Boolean exposeInSqllab = null;

  @SerializedName("extra")
  private String extra = null;

  @SerializedName("force_ctas_schema")
  private String forceCtasSchema = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("impersonate_user")
  private Boolean impersonateUser = null;

  @SerializedName("is_managed_externally")
  private Boolean isManagedExternally = null;

  @SerializedName("parameters")
  private Object parameters = null;

  @SerializedName("parameters_schema")
  private Object parametersSchema = null;

  @SerializedName("server_cert")
  private String serverCert = null;

  @SerializedName("sqlalchemy_uri")
  private String sqlalchemyUri = null;

  public DatabaseRestApiGet allowCtas(Boolean allowCtas) {
    this.allowCtas = allowCtas;
    return this;
  }

   /**
   * Get allowCtas
   * @return allowCtas
  **/
  @Schema(description = "")
  public Boolean isAllowCtas() {
    return allowCtas;
  }

  public void setAllowCtas(Boolean allowCtas) {
    this.allowCtas = allowCtas;
  }

  public DatabaseRestApiGet allowCvas(Boolean allowCvas) {
    this.allowCvas = allowCvas;
    return this;
  }

   /**
   * Get allowCvas
   * @return allowCvas
  **/
  @Schema(description = "")
  public Boolean isAllowCvas() {
    return allowCvas;
  }

  public void setAllowCvas(Boolean allowCvas) {
    this.allowCvas = allowCvas;
  }

  public DatabaseRestApiGet allowDml(Boolean allowDml) {
    this.allowDml = allowDml;
    return this;
  }

   /**
   * Get allowDml
   * @return allowDml
  **/
  @Schema(description = "")
  public Boolean isAllowDml() {
    return allowDml;
  }

  public void setAllowDml(Boolean allowDml) {
    this.allowDml = allowDml;
  }

  public DatabaseRestApiGet allowFileUpload(Boolean allowFileUpload) {
    this.allowFileUpload = allowFileUpload;
    return this;
  }

   /**
   * Get allowFileUpload
   * @return allowFileUpload
  **/
  @Schema(description = "")
  public Boolean isAllowFileUpload() {
    return allowFileUpload;
  }

  public void setAllowFileUpload(Boolean allowFileUpload) {
    this.allowFileUpload = allowFileUpload;
  }

  public DatabaseRestApiGet allowMultiSchemaMetadataFetch(Boolean allowMultiSchemaMetadataFetch) {
    this.allowMultiSchemaMetadataFetch = allowMultiSchemaMetadataFetch;
    return this;
  }

   /**
   * Get allowMultiSchemaMetadataFetch
   * @return allowMultiSchemaMetadataFetch
  **/
  @Schema(description = "")
  public Boolean isAllowMultiSchemaMetadataFetch() {
    return allowMultiSchemaMetadataFetch;
  }

  public void setAllowMultiSchemaMetadataFetch(Boolean allowMultiSchemaMetadataFetch) {
    this.allowMultiSchemaMetadataFetch = allowMultiSchemaMetadataFetch;
  }

  public DatabaseRestApiGet allowRunAsync(Boolean allowRunAsync) {
    this.allowRunAsync = allowRunAsync;
    return this;
  }

   /**
   * Get allowRunAsync
   * @return allowRunAsync
  **/
  @Schema(description = "")
  public Boolean isAllowRunAsync() {
    return allowRunAsync;
  }

  public void setAllowRunAsync(Boolean allowRunAsync) {
    this.allowRunAsync = allowRunAsync;
  }

   /**
   * Get backend
   * @return backend
  **/
  @Schema(description = "")
  public Object getBackend() {
    return backend;
  }

  public DatabaseRestApiGet cacheTimeout(Integer cacheTimeout) {
    this.cacheTimeout = cacheTimeout;
    return this;
  }

   /**
   * Get cacheTimeout
   * @return cacheTimeout
  **/
  @Schema(description = "")
  public Integer getCacheTimeout() {
    return cacheTimeout;
  }

  public void setCacheTimeout(Integer cacheTimeout) {
    this.cacheTimeout = cacheTimeout;
  }

  public DatabaseRestApiGet configurationMethod(String configurationMethod) {
    this.configurationMethod = configurationMethod;
    return this;
  }

   /**
   * Get configurationMethod
   * @return configurationMethod
  **/
  @Schema(description = "")
  public String getConfigurationMethod() {
    return configurationMethod;
  }

  public void setConfigurationMethod(String configurationMethod) {
    this.configurationMethod = configurationMethod;
  }

  public DatabaseRestApiGet databaseName(String databaseName) {
    this.databaseName = databaseName;
    return this;
  }

   /**
   * Get databaseName
   * @return databaseName
  **/
  @Schema(required = true, description = "")
  public String getDatabaseName() {
    return databaseName;
  }

  public void setDatabaseName(String databaseName) {
    this.databaseName = databaseName;
  }

  public DatabaseRestApiGet encryptedExtra(String encryptedExtra) {
    this.encryptedExtra = encryptedExtra;
    return this;
  }

   /**
   * Get encryptedExtra
   * @return encryptedExtra
  **/
  @Schema(description = "")
  public String getEncryptedExtra() {
    return encryptedExtra;
  }

  public void setEncryptedExtra(String encryptedExtra) {
    this.encryptedExtra = encryptedExtra;
  }

  public DatabaseRestApiGet exposeInSqllab(Boolean exposeInSqllab) {
    this.exposeInSqllab = exposeInSqllab;
    return this;
  }

   /**
   * Get exposeInSqllab
   * @return exposeInSqllab
  **/
  @Schema(description = "")
  public Boolean isExposeInSqllab() {
    return exposeInSqllab;
  }

  public void setExposeInSqllab(Boolean exposeInSqllab) {
    this.exposeInSqllab = exposeInSqllab;
  }

  public DatabaseRestApiGet extra(String extra) {
    this.extra = extra;
    return this;
  }

   /**
   * Get extra
   * @return extra
  **/
  @Schema(description = "")
  public String getExtra() {
    return extra;
  }

  public void setExtra(String extra) {
    this.extra = extra;
  }

  public DatabaseRestApiGet forceCtasSchema(String forceCtasSchema) {
    this.forceCtasSchema = forceCtasSchema;
    return this;
  }

   /**
   * Get forceCtasSchema
   * @return forceCtasSchema
  **/
  @Schema(description = "")
  public String getForceCtasSchema() {
    return forceCtasSchema;
  }

  public void setForceCtasSchema(String forceCtasSchema) {
    this.forceCtasSchema = forceCtasSchema;
  }

  public DatabaseRestApiGet id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public DatabaseRestApiGet impersonateUser(Boolean impersonateUser) {
    this.impersonateUser = impersonateUser;
    return this;
  }

   /**
   * Get impersonateUser
   * @return impersonateUser
  **/
  @Schema(description = "")
  public Boolean isImpersonateUser() {
    return impersonateUser;
  }

  public void setImpersonateUser(Boolean impersonateUser) {
    this.impersonateUser = impersonateUser;
  }

  public DatabaseRestApiGet isManagedExternally(Boolean isManagedExternally) {
    this.isManagedExternally = isManagedExternally;
    return this;
  }

   /**
   * Get isManagedExternally
   * @return isManagedExternally
  **/
  @Schema(description = "")
  public Boolean isIsManagedExternally() {
    return isManagedExternally;
  }

  public void setIsManagedExternally(Boolean isManagedExternally) {
    this.isManagedExternally = isManagedExternally;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @Schema(description = "")
  public Object getParameters() {
    return parameters;
  }

   /**
   * Get parametersSchema
   * @return parametersSchema
  **/
  @Schema(description = "")
  public Object getParametersSchema() {
    return parametersSchema;
  }

  public DatabaseRestApiGet serverCert(String serverCert) {
    this.serverCert = serverCert;
    return this;
  }

   /**
   * Get serverCert
   * @return serverCert
  **/
  @Schema(description = "")
  public String getServerCert() {
    return serverCert;
  }

  public void setServerCert(String serverCert) {
    this.serverCert = serverCert;
  }

  public DatabaseRestApiGet sqlalchemyUri(String sqlalchemyUri) {
    this.sqlalchemyUri = sqlalchemyUri;
    return this;
  }

   /**
   * Get sqlalchemyUri
   * @return sqlalchemyUri
  **/
  @Schema(required = true, description = "")
  public String getSqlalchemyUri() {
    return sqlalchemyUri;
  }

  public void setSqlalchemyUri(String sqlalchemyUri) {
    this.sqlalchemyUri = sqlalchemyUri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatabaseRestApiGet databaseRestApiGet = (DatabaseRestApiGet) o;
    return Objects.equals(this.allowCtas, databaseRestApiGet.allowCtas) &&
        Objects.equals(this.allowCvas, databaseRestApiGet.allowCvas) &&
        Objects.equals(this.allowDml, databaseRestApiGet.allowDml) &&
        Objects.equals(this.allowFileUpload, databaseRestApiGet.allowFileUpload) &&
        Objects.equals(this.allowMultiSchemaMetadataFetch, databaseRestApiGet.allowMultiSchemaMetadataFetch) &&
        Objects.equals(this.allowRunAsync, databaseRestApiGet.allowRunAsync) &&
        Objects.equals(this.backend, databaseRestApiGet.backend) &&
        Objects.equals(this.cacheTimeout, databaseRestApiGet.cacheTimeout) &&
        Objects.equals(this.configurationMethod, databaseRestApiGet.configurationMethod) &&
        Objects.equals(this.databaseName, databaseRestApiGet.databaseName) &&
        Objects.equals(this.encryptedExtra, databaseRestApiGet.encryptedExtra) &&
        Objects.equals(this.exposeInSqllab, databaseRestApiGet.exposeInSqllab) &&
        Objects.equals(this.extra, databaseRestApiGet.extra) &&
        Objects.equals(this.forceCtasSchema, databaseRestApiGet.forceCtasSchema) &&
        Objects.equals(this.id, databaseRestApiGet.id) &&
        Objects.equals(this.impersonateUser, databaseRestApiGet.impersonateUser) &&
        Objects.equals(this.isManagedExternally, databaseRestApiGet.isManagedExternally) &&
        Objects.equals(this.parameters, databaseRestApiGet.parameters) &&
        Objects.equals(this.parametersSchema, databaseRestApiGet.parametersSchema) &&
        Objects.equals(this.serverCert, databaseRestApiGet.serverCert) &&
        Objects.equals(this.sqlalchemyUri, databaseRestApiGet.sqlalchemyUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowCtas, allowCvas, allowDml, allowFileUpload, allowMultiSchemaMetadataFetch, allowRunAsync, backend, cacheTimeout, configurationMethod, databaseName, encryptedExtra, exposeInSqllab, extra, forceCtasSchema, id, impersonateUser, isManagedExternally, parameters, parametersSchema, serverCert, sqlalchemyUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatabaseRestApiGet {\n");
    
    sb.append("    allowCtas: ").append(toIndentedString(allowCtas)).append("\n");
    sb.append("    allowCvas: ").append(toIndentedString(allowCvas)).append("\n");
    sb.append("    allowDml: ").append(toIndentedString(allowDml)).append("\n");
    sb.append("    allowFileUpload: ").append(toIndentedString(allowFileUpload)).append("\n");
    sb.append("    allowMultiSchemaMetadataFetch: ").append(toIndentedString(allowMultiSchemaMetadataFetch)).append("\n");
    sb.append("    allowRunAsync: ").append(toIndentedString(allowRunAsync)).append("\n");
    sb.append("    backend: ").append(toIndentedString(backend)).append("\n");
    sb.append("    cacheTimeout: ").append(toIndentedString(cacheTimeout)).append("\n");
    sb.append("    configurationMethod: ").append(toIndentedString(configurationMethod)).append("\n");
    sb.append("    databaseName: ").append(toIndentedString(databaseName)).append("\n");
    sb.append("    encryptedExtra: ").append(toIndentedString(encryptedExtra)).append("\n");
    sb.append("    exposeInSqllab: ").append(toIndentedString(exposeInSqllab)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("    forceCtasSchema: ").append(toIndentedString(forceCtasSchema)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    impersonateUser: ").append(toIndentedString(impersonateUser)).append("\n");
    sb.append("    isManagedExternally: ").append(toIndentedString(isManagedExternally)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    parametersSchema: ").append(toIndentedString(parametersSchema)).append("\n");
    sb.append("    serverCert: ").append(toIndentedString(serverCert)).append("\n");
    sb.append("    sqlalchemyUri: ").append(toIndentedString(sqlalchemyUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
