/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.List;
import java.util.Objects;
import java.util.Arrays;
import at.mic.superset.swagger.client.model.DatasetRestApiGetDatabase;
import at.mic.superset.swagger.client.model.DatasetRestApiGetSqlMetric;
import at.mic.superset.swagger.client.model.DatasetRestApiGetTableColumn;
import at.mic.superset.swagger.client.model.DatasetRestApiGetUser;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DatasetRestApiGet
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-08-29T14:48:42.974+02:00[Europe/Berlin]")
public class DatasetRestApiGet {
  @SerializedName("cache_timeout")
  private Integer cacheTimeout = null;

  @SerializedName("columns")
  private DatasetRestApiGetTableColumn columns = null;

  @SerializedName("database")
  private DatasetRestApiGetDatabase database = null;

  @SerializedName("datasource_type")
  private Object datasourceType = null;

  @SerializedName("default_endpoint")
  private String defaultEndpoint = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("extra")
  private String extra = null;

  @SerializedName("fetch_values_predicate")
  private String fetchValuesPredicate = null;

  @SerializedName("filter_select_enabled")
  private Boolean filterSelectEnabled = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("is_managed_externally")
  private Boolean isManagedExternally = null;

  @SerializedName("is_sqllab_view")
  private Boolean isSqllabView = null;

  @SerializedName("kind")
  private Object kind = null;

  @SerializedName("main_dttm_col")
  private String mainDttmCol = null;

  @SerializedName("metrics")
  private DatasetRestApiGetSqlMetric metrics = null;

  @SerializedName("offset")
  private Integer offset = null;

  @SerializedName("owners")
  private List<DatasetRestApiGetUser> owners = null;

  @SerializedName("schema")
  private String schema = null;

  @SerializedName("sql")
  private String sql = null;

  @SerializedName("table_name")
  private String tableName = null;

  @SerializedName("template_params")
  private String templateParams = null;

  @SerializedName("url")
  private Object url = null;

  public DatasetRestApiGet cacheTimeout(Integer cacheTimeout) {
    this.cacheTimeout = cacheTimeout;
    return this;
  }

   /**
   * Get cacheTimeout
   * @return cacheTimeout
  **/
  @Schema(description = "")
  public Integer getCacheTimeout() {
    return cacheTimeout;
  }

  public void setCacheTimeout(Integer cacheTimeout) {
    this.cacheTimeout = cacheTimeout;
  }

  public DatasetRestApiGet columns(DatasetRestApiGetTableColumn columns) {
    this.columns = columns;
    return this;
  }

   /**
   * Get columns
   * @return columns
  **/
  @Schema(required = true, description = "")
  public DatasetRestApiGetTableColumn getColumns() {
    return columns;
  }

  public void setColumns(DatasetRestApiGetTableColumn columns) {
    this.columns = columns;
  }

  public DatasetRestApiGet database(DatasetRestApiGetDatabase database) {
    this.database = database;
    return this;
  }

   /**
   * Get database
   * @return database
  **/
  @Schema(required = true, description = "")
  public DatasetRestApiGetDatabase getDatabase() {
    return database;
  }

  public void setDatabase(DatasetRestApiGetDatabase database) {
    this.database = database;
  }

   /**
   * Get datasourceType
   * @return datasourceType
  **/
  @Schema(description = "")
  public Object getDatasourceType() {
    return datasourceType;
  }

  public DatasetRestApiGet defaultEndpoint(String defaultEndpoint) {
    this.defaultEndpoint = defaultEndpoint;
    return this;
  }

   /**
   * Get defaultEndpoint
   * @return defaultEndpoint
  **/
  @Schema(description = "")
  public String getDefaultEndpoint() {
    return defaultEndpoint;
  }

  public void setDefaultEndpoint(String defaultEndpoint) {
    this.defaultEndpoint = defaultEndpoint;
  }

  public DatasetRestApiGet description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DatasetRestApiGet extra(String extra) {
    this.extra = extra;
    return this;
  }

   /**
   * Get extra
   * @return extra
  **/
  @Schema(description = "")
  public String getExtra() {
    return extra;
  }

  public void setExtra(String extra) {
    this.extra = extra;
  }

  public DatasetRestApiGet fetchValuesPredicate(String fetchValuesPredicate) {
    this.fetchValuesPredicate = fetchValuesPredicate;
    return this;
  }

   /**
   * Get fetchValuesPredicate
   * @return fetchValuesPredicate
  **/
  @Schema(description = "")
  public String getFetchValuesPredicate() {
    return fetchValuesPredicate;
  }

  public void setFetchValuesPredicate(String fetchValuesPredicate) {
    this.fetchValuesPredicate = fetchValuesPredicate;
  }

  public DatasetRestApiGet filterSelectEnabled(Boolean filterSelectEnabled) {
    this.filterSelectEnabled = filterSelectEnabled;
    return this;
  }

   /**
   * Get filterSelectEnabled
   * @return filterSelectEnabled
  **/
  @Schema(description = "")
  public Boolean isFilterSelectEnabled() {
    return filterSelectEnabled;
  }

  public void setFilterSelectEnabled(Boolean filterSelectEnabled) {
    this.filterSelectEnabled = filterSelectEnabled;
  }

  public DatasetRestApiGet id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public DatasetRestApiGet isManagedExternally(Boolean isManagedExternally) {
    this.isManagedExternally = isManagedExternally;
    return this;
  }

   /**
   * Get isManagedExternally
   * @return isManagedExternally
  **/
  @Schema(description = "")
  public Boolean isIsManagedExternally() {
    return isManagedExternally;
  }

  public void setIsManagedExternally(Boolean isManagedExternally) {
    this.isManagedExternally = isManagedExternally;
  }

  public DatasetRestApiGet isSqllabView(Boolean isSqllabView) {
    this.isSqllabView = isSqllabView;
    return this;
  }

   /**
   * Get isSqllabView
   * @return isSqllabView
  **/
  @Schema(description = "")
  public Boolean isIsSqllabView() {
    return isSqllabView;
  }

  public void setIsSqllabView(Boolean isSqllabView) {
    this.isSqllabView = isSqllabView;
  }

   /**
   * Get kind
   * @return kind
  **/
  @Schema(description = "")
  public Object getKind() {
    return kind;
  }

  public DatasetRestApiGet mainDttmCol(String mainDttmCol) {
    this.mainDttmCol = mainDttmCol;
    return this;
  }

   /**
   * Get mainDttmCol
   * @return mainDttmCol
  **/
  @Schema(description = "")
  public String getMainDttmCol() {
    return mainDttmCol;
  }

  public void setMainDttmCol(String mainDttmCol) {
    this.mainDttmCol = mainDttmCol;
  }

  public DatasetRestApiGet metrics(DatasetRestApiGetSqlMetric metrics) {
    this.metrics = metrics;
    return this;
  }

   /**
   * Get metrics
   * @return metrics
  **/
  @Schema(required = true, description = "")
  public DatasetRestApiGetSqlMetric getMetrics() {
    return metrics;
  }

  public void setMetrics(DatasetRestApiGetSqlMetric metrics) {
    this.metrics = metrics;
  }

  public DatasetRestApiGet offset(Integer offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Get offset
   * @return offset
  **/
  @Schema(description = "")
  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public DatasetRestApiGet owners(List<DatasetRestApiGetUser> owners) {
    this.owners = owners;
    return this;
  }

   /**
   * Get owners
   * @return owners
  **/
  @Schema(description = "")
  public List<DatasetRestApiGetUser> getOwners() {
    return owners;
  }

  public void setOwners(List<DatasetRestApiGetUser> owners) {
    this.owners = owners;
  }

  public DatasetRestApiGet schema(String schema) {
    this.schema = schema;
    return this;
  }

   /**
   * Get schema
   * @return schema
  **/
  @Schema(description = "")
  public String getSchema() {
    return schema;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }

  public DatasetRestApiGet sql(String sql) {
    this.sql = sql;
    return this;
  }

   /**
   * Get sql
   * @return sql
  **/
  @Schema(description = "")
  public String getSql() {
    return sql;
  }

  public void setSql(String sql) {
    this.sql = sql;
  }

  public DatasetRestApiGet tableName(String tableName) {
    this.tableName = tableName;
    return this;
  }

   /**
   * Get tableName
   * @return tableName
  **/
  @Schema(required = true, description = "")
  public String getTableName() {
    return tableName;
  }

  public void setTableName(String tableName) {
    this.tableName = tableName;
  }

  public DatasetRestApiGet templateParams(String templateParams) {
    this.templateParams = templateParams;
    return this;
  }

   /**
   * Get templateParams
   * @return templateParams
  **/
  @Schema(description = "")
  public String getTemplateParams() {
    return templateParams;
  }

  public void setTemplateParams(String templateParams) {
    this.templateParams = templateParams;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public Object getUrl() {
    return url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetRestApiGet datasetRestApiGet = (DatasetRestApiGet) o;
    return Objects.equals(this.cacheTimeout, datasetRestApiGet.cacheTimeout) &&
        Objects.equals(this.columns, datasetRestApiGet.columns) &&
        Objects.equals(this.database, datasetRestApiGet.database) &&
        Objects.equals(this.datasourceType, datasetRestApiGet.datasourceType) &&
        Objects.equals(this.defaultEndpoint, datasetRestApiGet.defaultEndpoint) &&
        Objects.equals(this.description, datasetRestApiGet.description) &&
        Objects.equals(this.extra, datasetRestApiGet.extra) &&
        Objects.equals(this.fetchValuesPredicate, datasetRestApiGet.fetchValuesPredicate) &&
        Objects.equals(this.filterSelectEnabled, datasetRestApiGet.filterSelectEnabled) &&
        Objects.equals(this.id, datasetRestApiGet.id) &&
        Objects.equals(this.isManagedExternally, datasetRestApiGet.isManagedExternally) &&
        Objects.equals(this.isSqllabView, datasetRestApiGet.isSqllabView) &&
        Objects.equals(this.kind, datasetRestApiGet.kind) &&
        Objects.equals(this.mainDttmCol, datasetRestApiGet.mainDttmCol) &&
        Objects.equals(this.metrics, datasetRestApiGet.metrics) &&
        Objects.equals(this.offset, datasetRestApiGet.offset) &&
        Objects.equals(this.owners, datasetRestApiGet.owners) &&
        Objects.equals(this.schema, datasetRestApiGet.schema) &&
        Objects.equals(this.sql, datasetRestApiGet.sql) &&
        Objects.equals(this.tableName, datasetRestApiGet.tableName) &&
        Objects.equals(this.templateParams, datasetRestApiGet.templateParams) &&
        Objects.equals(this.url, datasetRestApiGet.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cacheTimeout, columns, database, datasourceType, defaultEndpoint, description, extra, fetchValuesPredicate, filterSelectEnabled, id, isManagedExternally, isSqllabView, kind, mainDttmCol, metrics, offset, owners, schema, sql, tableName, templateParams, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetRestApiGet {\n");
    
    sb.append("    cacheTimeout: ").append(toIndentedString(cacheTimeout)).append("\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    database: ").append(toIndentedString(database)).append("\n");
    sb.append("    datasourceType: ").append(toIndentedString(datasourceType)).append("\n");
    sb.append("    defaultEndpoint: ").append(toIndentedString(defaultEndpoint)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("    fetchValuesPredicate: ").append(toIndentedString(fetchValuesPredicate)).append("\n");
    sb.append("    filterSelectEnabled: ").append(toIndentedString(filterSelectEnabled)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isManagedExternally: ").append(toIndentedString(isManagedExternally)).append("\n");
    sb.append("    isSqllabView: ").append(toIndentedString(isSqllabView)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    mainDttmCol: ").append(toIndentedString(mainDttmCol)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    owners: ").append(toIndentedString(owners)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    sql: ").append(toIndentedString(sql)).append("\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("    templateParams: ").append(toIndentedString(templateParams)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
