/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import at.mic.superset.swagger.client.model.SavedQueryRestApiGetDatabase;
import at.mic.superset.swagger.client.model.SavedQueryRestApiGetUser;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SavedQueryRestApiGet
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-08-29T14:48:42.974+02:00[Europe/Berlin]")
public class SavedQueryRestApiGet {
  @SerializedName("created_by")
  private SavedQueryRestApiGetUser createdBy = null;

  @SerializedName("database")
  private SavedQueryRestApiGetDatabase database = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("schema")
  private String schema = null;

  @SerializedName("sql")
  private String sql = null;

  @SerializedName("sql_tables")
  private Object sqlTables = null;

  public SavedQueryRestApiGet createdBy(SavedQueryRestApiGetUser createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @Schema(description = "")
  public SavedQueryRestApiGetUser getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(SavedQueryRestApiGetUser createdBy) {
    this.createdBy = createdBy;
  }

  public SavedQueryRestApiGet database(SavedQueryRestApiGetDatabase database) {
    this.database = database;
    return this;
  }

   /**
   * Get database
   * @return database
  **/
  @Schema(description = "")
  public SavedQueryRestApiGetDatabase getDatabase() {
    return database;
  }

  public void setDatabase(SavedQueryRestApiGetDatabase database) {
    this.database = database;
  }

  public SavedQueryRestApiGet description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SavedQueryRestApiGet id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public SavedQueryRestApiGet label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public SavedQueryRestApiGet schema(String schema) {
    this.schema = schema;
    return this;
  }

   /**
   * Get schema
   * @return schema
  **/
  @Schema(description = "")
  public String getSchema() {
    return schema;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }

  public SavedQueryRestApiGet sql(String sql) {
    this.sql = sql;
    return this;
  }

   /**
   * Get sql
   * @return sql
  **/
  @Schema(description = "")
  public String getSql() {
    return sql;
  }

  public void setSql(String sql) {
    this.sql = sql;
  }

   /**
   * Get sqlTables
   * @return sqlTables
  **/
  @Schema(description = "")
  public Object getSqlTables() {
    return sqlTables;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SavedQueryRestApiGet savedQueryRestApiGet = (SavedQueryRestApiGet) o;
    return Objects.equals(this.createdBy, savedQueryRestApiGet.createdBy) &&
        Objects.equals(this.database, savedQueryRestApiGet.database) &&
        Objects.equals(this.description, savedQueryRestApiGet.description) &&
        Objects.equals(this.id, savedQueryRestApiGet.id) &&
        Objects.equals(this.label, savedQueryRestApiGet.label) &&
        Objects.equals(this.schema, savedQueryRestApiGet.schema) &&
        Objects.equals(this.sql, savedQueryRestApiGet.sql) &&
        Objects.equals(this.sqlTables, savedQueryRestApiGet.sqlTables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, database, description, id, label, schema, sql, sqlTables);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SavedQueryRestApiGet {\n");
    
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    database: ").append(toIndentedString(database)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    sql: ").append(toIndentedString(sql)).append("\n");
    sb.append("    sqlTables: ").append(toIndentedString(sqlTables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
